apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret-test
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store 

  target:
    name: gitlab-secret-to-create 
    creationPolicy: Owner

  data:
    - secretKey: secretKey 
      remoteRef: 
        key: myGitlabVariable 
